### ISSUE TITLE
billing option

### ISSUE THREAD

**Issue by ghost** [syedamir91/ups-api#1]
it throws an error "A single billing option is required per shipment.", can we check what is the problem?

**Comment by syedamir91** [comment]
If you are creating a shipment, you need to provide a valid billing address, its mandatory.

**Comment by ghost** [comment]
the address is valid, I commented this part 
$shipmentcharge['Type'] = '01';
//        $creditcard['Type'] = '06';
//        $creditcard['Number'] = $this->CI->config->item('ups')['cc']['CC_Number'];
//        $creditcard['SecurityCode'] = $this->CI->config->item('ups')['cc']['CC_SecurityCode'];
//        $creditcard['ExpirationDate'] = $this->CI->config->item('ups')['cc']['CC_ExpirationDate'];
//        $creditCardAddress['AddressLine'] = $this->CI->config->item('ups')['cc']['CC_AddressLine'];
//        $creditCardAddress['City'] = $this->CI->config->item('ups')['cc']['CC_City'];
//        $creditCardAddress['StateProvinceCode'] = $this->CI->config->item('ups')['cc']['CC_StateProvinceCode'];
//        $creditCardAddress['PostalCode'] = $this->CI->config->item('ups')['cc']['CC_PostalCode'];
//        $creditCardAddress['CountryCode'] = $this->CI->config->item('ups')['cc']['CC_CountryCode'];
//        $creditcard['Address'] = $creditCardAddress;
//        $billshipper['CreditCard'] = $creditcard;
//        $shipmentcharge['BillShipper'] = $billshipper;
//        $paymentinformation['ShipmentCharge'] = $shipmentcharge;
//        $shipment['PaymentInformation'] = $paymentinformation;
because there is not anywhere in config "cc"

**Comment by syedamir91** [comment]
You have to pass your billing details, don't comment Credit Card information, to create shipment it is mandatory.

**Comment by ghost** [comment]
if I'm just testing will it still charge me?

**Comment by ghost** [comment]
sorry, one more question, are you developing this API or not anymore?

**Comment by syedamir91** [comment]
In "test" mode you can put test credit card numbers.

Check it in your config file:

**'mode' => 'test' // production**

For UPS three services(Rate, Ship and Track) this API is done.

If you have any more queries, I would like to help you.

**Comment by ghost** [comment]
thank you. I will finish for these three services and try to do more, there will be any questions I'll ask you. Thanks a lot
